# local.yml

services:
  app:
    build:
      context: .
      dockerfile: ./compose/openoutreach/Dockerfile
      args:
        - BUILD_ENV=local
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    volumes:
      - .:/app
