# local.yml

services:
  app:
    build:
      context: .
      dockerfile: ./compose/linkedin/Dockerfile
      args:
        - BUILD_ENV=local
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    ports:
      - "5900:5900"
