# Generated by Django 6.0.6 on 2026-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="imap_host",
            field=models.CharField(default="imap.gmail.com", max_length=255),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="imap_port",
            field=models.PositiveIntegerField(default=993),
        ),
    ]
