# Generated by Django 6.0.6 on 2026-07-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
