# Generated by Django 6.0.3 on 2026-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_urn_to_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='external_id',
            field=models.CharField(help_text='Message identity, used for dedup (per deal): the RFC-5322 Message-ID of the email. (Legacy LinkedIn rows hold a Voyager entityUrn.)', max_length=300, verbose_name='External message id'),
        ),
    ]
