# Generated by Django 6.1 on 2026-08-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="profile_summary",
        ),
    ]
