# Generated by Django 6.1 on 2026-08-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_deal_lookup_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="state",
            field=models.CharField(
                choices=[
                    ("Qualified", "Qualified"),
                    ("Ready to Find Email", "Ready To Find Email"),
                    ("Finding Email", "Finding Email"),
                    ("Resolved", "Resolved"),
                    ("No Email Found", "No Email Found"),
                    ("Failed", "Failed"),
                ],
                default="Qualified",
                max_length=32,
            ),
        ),
    ]
