# Generated by Django 5.2.16 on 2026-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_pivot_lead_reshape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Ready to Find Email', 'Ready To Find Email'), ('Finding Email', 'Finding Email'), ('Ready to Email', 'Ready To Email'), ('Sending Email', 'Sending Email'), ('Emailed', 'Emailed'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Qualified', max_length=20),
        ),
    ]
