# Generated by Django 6.0.6 on 2026-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_lead_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="next_follow_up_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="state",
            field=models.CharField(
                choices=[
                    ("Qualified", "Qualified"),
                    ("Ready to Find Email", "Ready To Find Email"),
                    ("Ready to Email", "Ready To Email"),
                    ("Emailed", "Emailed"),
                    ("Ready to Connect", "Ready To Connect"),
                    ("Pending", "Pending"),
                    ("Connected", "Connected"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Qualified",
                max_length=20,
            ),
        ),
    ]
