# Generated by Django 6.0.6 on 2026-07-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0011_linkedinprofile_contribute_to_hub"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="actionlog",
            name="linkedin_ac_linkedi_37318d_idx",
        ),
        migrations.RemoveField(
            model_name="linkedinprofile",
            name="self_lead",
        ),
        migrations.RemoveField(
            model_name="linkedinprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="actionlog",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="actionlog",
            name="linkedin_profile",
        ),
        migrations.DeleteModel(
            name="SearchKeyword",
        ),
        migrations.DeleteModel(
            name="ActionLog",
        ),
        migrations.DeleteModel(
            name="LinkedInProfile",
        ),
    ]
