# Generated by Django 5.2.12 on 2026-04-06 06:40

import linkedin.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_public_identifier_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Ready to Connect', 'Ready to Connect'), ('Pending', 'Pending'), ('Connected', 'Connected'), ('Completed', 'Completed'), ('Failed', 'Failed')], default=linkedin.enums.ProfileState['QUALIFIED'], max_length=20),
        ),
    ]
