# Generated by Django 6.0.3 on 2026-04-11 18:49

from django.db import migrations, models


def backfill_urn_from_profile_data(apps, schema_editor):
    """Promote profile_data['urn'] into the new Lead.urn column."""
    Lead = apps.get_model("crm", "Lead")
    updates = []
    for lead in Lead.objects.exclude(profile_data=None).only("pk", "profile_data", "urn").iterator():
        urn = (lead.profile_data or {}).get("urn")
        if urn and lead.urn != urn:
            lead.urn = urn
            updates.append(lead)
            if len(updates) >= 500:
                Lead.objects.bulk_update(updates, ["urn"])
                updates.clear()
    if updates:
        Lead.objects.bulk_update(updates, ["urn"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_deal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='urn',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(backfill_urn_from_profile_data, migrations.RunPython.noop),
    ]
