# Generated by Django 5.2.11 on 2026-02-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_alter_reminder_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_docs', models.TextField(blank=True)),
                ('campaign_objective', models.TextField(blank=True)),
                ('followup_template', models.TextField(blank=True)),
                ('booking_link', models.URLField(blank=True, max_length=500)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='common.department')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_username', models.CharField(max_length=200)),
                ('linkedin_password', models.CharField(max_length=200)),
                ('subscribe_newsletter', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('connect_daily_limit', models.PositiveIntegerField(default=20)),
                ('connect_weekly_limit', models.PositiveIntegerField(default=100)),
                ('follow_up_daily_limit', models.PositiveIntegerField(default=30)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='linkedin.campaign')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
