# Generated by Django 6.0.5 on 2026-05-25 05:20

import linkedin.tz_detect
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='active_end_hour',
            field=models.PositiveSmallIntegerField(default=19, help_text='Exclusive, 0-23 local time.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='active_start_hour',
            field=models.PositiveSmallIntegerField(default=9, help_text='Inclusive, 0-23 local time.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='active_timezone',
            field=models.CharField(default=linkedin.tz_detect.system_timezone, help_text="IANA timezone name (e.g. 'America/New_York').", max_length=64),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enable_active_hours',
            field=models.BooleanField(default=True, help_text='Pause the daemon outside the active window.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='rest_days',
            field=models.JSONField(blank=True, default=list, help_text='List of weekday ints (0=Mon … 6=Sun) to pause on.'),
        ),
    ]
