# Generated by Django 6.0.3 on 2026-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0009_backfill_embedding_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("connect", "Connect"),
                            ("check_pending", "Check Pending"),
                            ("follow_up", "Follow Up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="actionlog",
            new_name="linkedin_ac_linkedi_37318d_idx",
            old_name="linkedin_act_linkedi_idx",
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "scheduled_at"], name="linkedin_ta_status_d04eec_idx"
            ),
        ),
    ]
