# Generated by Django 6.0.3 on 2026-03-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='action_fraction',
            field=models.FloatField(default=0.2),
        ),
    ]
