# Generated by Django 6.0.3 on 2026-03-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0011_action_fraction_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="legal_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
