# Generated by Django 6.0.3 on 2026-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0015_remove_followup_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="seed_public_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
