# Generated by Django 6.1 on 2026-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfig_apollo_api_key_siteconfig_email_finder"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="anchor_source_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
