# Generated by Django 5.2.16 on 2026-07-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_campaign_objective_campaign_campaign_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='planned', max_length=20)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['action_type', 'status'], name='core_action_type_status_idx'), models.Index(fields=['created_at'], name='core_action_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('action_type', 'idempotency_key'), name='unique_action_idempotency_key')],
            },
        ),
    ]
