# Generated by Django 6.0.6 on 2026-07-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_frontier_drop_legacy_cursor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryquery',
            name='score',
        ),
    ]
