# Generated by Django 6.0.6 on 2026-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteconfig_provider_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("find_email", "Find Email"),
                    ("follow_up", "Follow Up"),
                    ("email", "Email"),
                ],
                max_length=20,
            ),
        ),
    ]
