# Generated by Django 6.0.6 on 2026-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_siteconfig_country_code_alter_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="discovery_offset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="icp_filters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
