# Generated by hand — see the roadmap card p2-e3-discovery-query-graph-search.
"""A discovery node stops being an opaque filter blob and becomes a set of clauses.

``params`` was a JSON dict, and you cannot ``GROUP BY`` a clause inside a blob —
which is the only query the walk's design needs to be fast. It could also express
an include-list (an OR), and an OR is strictly dominated: a filter does not narrow
a result set, it *moves a ~10k-row sampling window* over a corpus ordered by
provider preference, so five titles ORed into one query see one window where five
separate queries would see five, for free.

**Every existing node is deleted, deliberately.** All of them carry include-lists
(the seed was ``job_title: [Founder, Growth Manager, SDR, Head of Growth, Technical
Founder]``) and are simply not representable under one clause per family; there is
no honest migration of an OR into a conjunction. ``Lead.discovered_by`` is
``SET_NULL``, so **every Lead survives and every label survives** — labels live on
``Deal``, not on the node. What is lost is discovery provenance: which query first
touched which lead. The walk restarts from a cold bootstrap and re-earns it.
"""
from django.db import migrations, models
import django.db.models.deletion


def erase_legacy_nodes(apps, schema_editor):
    """Drop every node. Leads survive (SET_NULL); their labels live on Deal."""
    apps.get_model("core", "DiscoveryQuery").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_discoveryquery_score"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(erase_legacy_nodes, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="discoveryquery", name="uniq_discovery_node",
        ),
        migrations.RemoveField(model_name="discoveryquery", name="params"),
        migrations.RemoveField(model_name="discoveryquery", name="params_hash"),
        migrations.CreateModel(
            name="Clause",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("family", models.CharField(choices=[
                    ("company_headcount_min", "company_headcount_min"),
                    ("company_headcount_max", "company_headcount_max"),
                    ("lead_job_title", "lead_job_title"),
                    ("lead_seniority", "lead_seniority"),
                    ("lead_location", "lead_location"),
                    ("lead_department", "lead_department"),
                    ("lead_function", "lead_function"),
                ], max_length=32)),
                ("value", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="clause",
            constraint=models.UniqueConstraint(
                fields=("family", "value"), name="uniq_clause",
            ),
        ),
        migrations.AddField(
            model_name="discoveryquery",
            name="clause_key",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoveryquery",
            name="clauses",
            field=models.ManyToManyField(related_name="queries", to="core.clause"),
        ),
        migrations.AddConstraint(
            model_name="discoveryquery",
            constraint=models.UniqueConstraint(
                fields=("campaign", "clause_key", "offset"), name="uniq_discovery_node",
            ),
        ),
    ]
