# Generated by Django 6.0.6 on 2026-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clause_discoveryquery_clauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clauses',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.clause'),
        ),
        migrations.AddField(
            model_name='clause',
            name='is_live',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='EmptyClauseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clauses', models.ManyToManyField(related_name='empty_sets', to='core.clause')),
            ],
            options={
                'verbose_name': 'Empty Clause Set',
                'verbose_name_plural': 'Empty Clause Sets',
            },
        ),
    ]
